name: Compile App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev mesa-common-dev libxtst-dev

      - name: Compile for Linux
        run: |
          mkdir build && cd build
          make ..

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-executable
          path: .


  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0
            

      - name: Compile for Windows
        run: |
          mkdir build && cd build
          vcpkg install imgui
          vcpkg install glfw3
          vcpkg integrate install
          msbuild ../RMB.sln

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: .
